    const products = {
      1: {
        name: "HNonline",
        slug: "hnonline",
        description: "Jediný ekonomický denník na Slovensku, ktorý svojím zameraním prináša seriózne a dôveryhodné informácie pre každého, koho zaujíma ekonomický pohľad na dianie doma a vo svete. Každý pracovný deň prinášajú aktuálne spravodajstvo, analýzy, štatistiky, prognózy a užitočné rady aj pre Váš druh podnikania.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_hnonline.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    2: {
        name: "Svetevity",
        description: "svetevity",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_svetevity.png",
        btnCennik: "Cenník",
        btnCennikUrl: "",  
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    3: {
        name: "Brainee",
        description: "brainee",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_brainee.png",
        btnCennik: "Cenník",
        btnCennikUrl: "",  
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    };