    const products = {
      1: {
        name: "HNonline",
        slug: "hnonline",
        description: "HN online, digitálna verzia denníka Hospodárske noviny, je garantom kvality, nestrannosti a dôveryhodnosti v oblasti ekonomického spravodajstva. Zameriava sa na poskytovanie komplexných, fakticky podložených informácií, ktoré čitateľom umožňujú lepšie porozumieť zložitým ekonomickým súvislostiam. Medzi hlavné hodnoty, na ktorých Hospodárske noviny dlhodobo stoja, patrí úcta k faktom a minimalizovanie emócií. Aj to je možno jeden z dôvodov, prečo ich čitatelia dlhodobo považujú za jedno z najdôveryhodnejších slovenských médií.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_hnonline.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Mafra_online_cennik_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne?utm_source=mafraweb", 
      },
    2: {
        name: "Brainee",
        description: "Web pre cieľovú skupinu 16 – 30 rokov, zameraný na mestského čitateľa, ktorý má rád kvalitnú kávu, za ktorú je ochotný zaplatiť, a zároveň si vyhľadáva lacné letenky. Nie je mu ľahostajná spoločenská a rodová rovnosť, sleduje Netflix, používa Instagram a zaujíma sa o klimatické zmeny vo svete.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_brainee.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Mafra_online_cennik_2025.pdf",  
        btnPred:"",
        btnPredUrl: "", 
      },
    3: {
        name: "Svetevity",
        description: "Svetevity.sk je online platforma, ktorá oslovuje aktívne ženy (25-55 rokov) so záujmom o lifestyle, módu, krásu, zdravie, vzťahy a rodinu. Obsah je ľahký, inšpiratívny a informatívny, čím si získava pozornosť čitateliek, ktoré hľadajú praktické rady a aktuálne trendy pre svoj každodenný život. Vďaka jasne profilovanej cieľovej skupine ponúkame partnerom ideálny priestor na budovanie povedomia o značke, predstavenie produktov a vytváranie engagementu prostredníctvom natívneho obsahu, súťaží, PR článkov či bannerových kampaní. Súčasťou portálu je online platforma zameraná na gastronómiu a varenie varimespolu.sk. Návštevníci nájdu overené recepty, kuchynské tipy, sezónne inšpirácie a nápady na rýchle a zdravé jedlá. Portál oslovuje publikum od začiatočníkov až po skúsených kuchárov, pričom kladie dôraz na aktuálnosť a sezónnosť publikovaných receptov. Portál je pre partnerov vhodnou možnosťou produktového placementu, branded contentu, spoluprác na receptoch, ktoré prirodzene oslovia našich čitateľov a posilnia pozitívne vnímanie vašej značky.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_svetevity.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Mafra_online_cennik_2025.pdf",  
        btnPred:"",
        btnPredUrl: "", 
      },
    };