    const products = {
      1: {
        name: "HNonline",
        slug: "hnonline",
        description: "HN online, digitálna verzia denníka Hospodárske noviny, je garantom kvality, nestrannosti a dôveryhodnosti v oblasti ekonomického spravodajstva. Zameriava sa na poskytovanie komplexných, fakticky podložených informácií, ktoré čitateľom umožňujú lepšie porozumieť zložitým ekonomickým súvislostiam. Medzi hlavné hodnoty, na ktorých Hospodárske noviny dlhodobo stoja, patrí úcta k faktom a minimalizovanie emócií. Aj to je možno jeden z dôvodov, prečo ich čitatelia dlhodobo považujú za jedno z najdôveryhodnejších slovenských médií.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_hnonline.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Mafra_online_cennik_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne?utm_source=mafraweb", 
      },
    2: {
        name: "Brainee",
        description: "Web pre cieľovú skupinu 16 – 30 rokov, zameraný na mestského čitateľa, ktorý má rád kvalitnú kávu, za ktorú je ochotný zaplatiť, a zároveň si vyhľadáva lacné letenky. Nie je mu ľahostajná spoločenská a rodová rovnosť, sleduje Netflix, používa Instagram a zaujíma sa o klimatické zmeny vo svete.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_brainee.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Mafra_online_cennik_2025.pdf",  
        btnPred:"",
        btnPredUrl: "", 
      },
    3: {
        name: "Svetevity",
        description: "Online platforma pre ženy (25-55 rokov), zameraná na lifestyle, módu, krásu, zdravie, vzťahy a rodinu. Obsah je ľahký, informatívny a inšpiratívny. Typická čitateľka je moderná, aktívna žena hľadajúca praktické rady a trendy pre každodenný život. varímespolu.sk je gastro web pre všetkých, ktorí milujú dobré jedlo a spoločné chvíle pri varení. Nájdete tu overené recepty, tipy do kuchyne, sezónne inšpirácie aj nápady na rýchle a zdravé jedlá. Či už ste začiatočník alebo skúsený kuchár, u nás si určite vyberiete.",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/port_svetevity.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Mafra_online_cennik_2025.pdf",  
        btnPred:"",
        btnPredUrl: "", 
      },
    };