    const products = {
      1: {
        name: "Hospodárske noviny",
        slug: "hospodarske-noviny",
        description: "Hospodárske noviny sú garantom kvality, nestrannosti a dôveryhodnosti v oblasti ekonomického spravodajstva. Zameriavajú sa na poskytovanie komplexných, fakticky podložených informácií, ktoré čitateľom umožňujú lepšie porozumieť zložitým ekonomickým súvislostiam. Medzi hlavné hodnoty, na ktorých Hospodárske noviny dlhodobo stoja, patria úcta k faktom a minimalizovanie emócií. Aj to je možno jeden z dôvodov, prečo ich čitatelia dlhodobo považujú za jedno z najdôveryhodnejších slovenských médií. ",
        zameranie: "Zameranie: Biznis & Lifestyle",
        vznik: "Vznik: 1993",
        periodicita: "Periodicita: denník",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/hospnoviny.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/dennik_hn.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/HN_harmonogram_2025%20komplet.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96015890-hospodarske-noviny",

        extraButtons: [ // tieto sa zobrazia stále priamo
          { label: "Titulná strana HN - cennik", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/titulka_hn.pdf", class: "product-detail-btn btn-pdf" },
          { label: "Povinná inzercia - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/povinna_inzercia.pdf", class: "product-detail-btn btn-video" },
          { label: "HN atypické formáty - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/atyp_formaty.pdf", class: "product-detail-btn btn-video" },
          { label: "HN prílohy A3 - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/prilohy_a3.pdf", class: "product-detail-btn btn-video" },
          { label: "HN prílohy A4 - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/prilohy_a4.pdf", class: "product-detail-btn btn-video" },
          { label: "HN atypické formáty - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/atyp_formaty.pdf", class: "product-detail-btn btn-video" },
            ],

        /*accordionButtonsTitle: "Materiály na stiahnutie", // voliteľné
        accordionButtons: [ // tieto budú v harmonike
          { label: "Špeciál 1", url: "#", class: "product-detail-btn btn-special" },
          { label: "Špeciál 2", url: "#", class: "product-detail-btn btn-special2" }
        ]*/
      },
    2: {
        name: "HN Magazín",
        description: "HN Magazín je samostatne nepredajná piatková príloha Hospodárskych novín. Prináša rozhovory s rešpektovanými osobnosťami, najnovšie poznatky zo sveta zdravia aj biznisu, odhaľuje spoločenské fenomény a zaujímavosti, ktoré hýbu svetom. Vďaka televíznemu programu a pohodovému čítaniu patrí k piatkovým rituálom mnohých čitateľov. ",
        zameranie: "Zameranie: Biznis & Lifestyle",
        vznik: "Vznik: 2015",
        periodicita: "Periodicita: týždenník, vkladaný do HN, samostatne nepredajný ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/hnmagazin.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/HNmagazin_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/HNmagazin_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    3: {
        name: "Prečo nie?!",
        description: "Exkluzívna príloha denníka Hospodárske noviny. Miesto pre náročných inzerentov.",
        zameranie: "Zameranie: Lifestyle",
        vznik: "Vznik: 2008",
        periodicita: "Periodicita: mesačník, vkladaný do HN, samostatne nepredajný ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/preconie.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/preco-nie_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/Preco-nie_harmonogram_2025%20nove.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    4: {
        name: "Svet 2025",
        description: "Lifestylový magazín Svet 2025 vychádza ako samostatná príloha denníka Hospodárske noviny, ktorá prináša pohľad na najväčšie domáce a svetové témy v nasledujúcom roku.",
        zameranie: "Zameranie: Biznis",
        vznik: "Vznik: 2011",
        periodicita: "Periodicita: ročenka, vkladaná do HN pre predplatiteľov a samostane predávaná ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tttttttttttt.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/svet-2025_promo.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    5: {
        name: "Stratégie",
        description: "Mesačník Stratégie je jediný časopis na slovenskom trhu, ktorý už 30 rokov ponúka profesionálny pohľad na mediálny, marketingový a reklamný trh na Slovensku a v zahraničí. Takmer každý mesiac vychádza nové číslo doplnené o špecializovanú prílohu. Má aj svoju digitálnu verziu a silnú komunikáciu na sociálnych sieťach.Kompendium medicíny (od roku 2000) je určené pre odbornú verejnosť – lekárov, farmaceutov a ďalších zdravotníckych pracovníkov, nemá pravidelnú periodicitu, pretože prináša podrobné informácie z domácich i zo zahraničných kongresov a sympózií, ako aj komplexné informácie od vybraných renomovaných autorov.",
        zameranie: "Zameranie: marketing, reklama, médiá",
        vznik: "Vznik: 1994",
        periodicita: "Periodicita: mesačník s tematickou prílohou ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/strategie.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/strategie_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/Strategie_harmonogram_2025%20najnovsi.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016053-strategie", 

        accordionButtonsTitle: "Stratégie prílohy", // voliteľné
        accordionButtons: [ // tieto budú v harmonike
          { label: "Stratégie prílohy - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/strategie_prilohy_cennik_2025.pdf", class: "product-detail-btn btn-special" },
          { label: "Stratégie prílohy - harmonogram", url: "https://mafraslovakia.hnonline.sk/files/title_schedule/strategie_harmonogram_2025_0.pdf", class: "product-detail-btn btn-special2" }
        ]
      },
    6: {
        name: "Diabetik",
        description: "Časopis je určený predovšetkým pacientom s diabetom, ich príbuzným, ale aj všetkým, ktorých zaujíma prevencia pred civilizačnými ochoreniami. Zároveň je užitočným pomocníkom pre diabetológov či diabetologické sestry pri edukácii pacientov.Na 68 stranách nájdu čitatelia aktuálne informácie z oblasti diabetológie, ale aj ďalších príbuzných medicínskych odborov. V každom čísle majú priestor rozhovory, príbehy pacientov, rubrika o racionálnom stravovaní, sociálno-právna poradňa, nové formy a metódy liečby diabetu a komplikácií súvisiacich s týmto ochorením a mnoho ďalších tém.",
        zameranie: "Zameranie: zdravie, zdravý životný štýl",
        vznik: "Vznik: 2002",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/diabetik.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/Cennik_DIABETIK_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/diabetik_harmonogram2025_0.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016056-diabetik", 
      },
    7: {
        name: "Horeca",
        description: "Tradičný odborný dvojmesačník HORECA magazine sa zaoberá problematikou hotelierstva, reštaurácií, gastronómie a stravovacích služieb.",
        zameranie: "Zameranie: hotelierstvo a gastronómia",
        vznik: "Vznik: 2004",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/horeca.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/horeca_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/Horeca_harmonogram_2025%20oprava.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/horeca_cennik_2025.pdf", 
      },
    8: {
        name: "Obchod",
        description: "Časopis Obchod sa zaoberá situáciou v maloobchodnom trhu: obchody, obchodné siete a reťazce.",
        zameranie: "Zameranie: maloobchod, veľkoobchod a internetový predaj",
        vznik: "Vznik: 1995",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/obchod.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/obchod_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/obchod_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016058-obchod", 
      },
    9: {
        name: "Zdravotnícke noviny",
        description: "Týždenník pre odbornú verejnosť – lekárov, farmaceutov a ďalších zdravotníckych pracovníkov už 30 rokov. Zdravotnícke noviny prinášajú novinky v zdravotníckej politike a legislatíve, nové trendy v diagnostike a liečbe. Na pravidelnej báze spolupracujú s najdôležitejšími lekárskymi asociáciami, informujú o ich činnostiach a aktivitách. Silná odborná kredibilita týždenníka je podporená špecializovanými medicínskymi magazínmi Lekárske listy, Kompendium medicíny a Medical Practice, ktoré sú súčasťou Zdravotníckych novín v špeciálnej periodicite.",
        zameranie: "Zameranie: zdravotníctvo",
        vznik: "Vznik: 1952",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/zdn.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/hn_cennik_2019_0312_zdn_c.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/zdn_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016060-zdravotnicke-noviny", 

        accordionButtonsTitle: "Lekárske listy | Medical practice | Kompendium medicíny", // voliteľné
        accordionButtons: [ // tieto budú v harmonike
          { label: "Lekárske listy - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/hn_cennik_2019_0312_ll_c.pdf", class: "product-detail-btn btn-special" },
          { label: "Lekárske listy - harmonogram", url: "https://mafraslovakia.hnonline.sk/files/title_schedule/LL%20+%20MP_harmonogram_2025.pdf", class: "product-detail-btn btn-special2" },
          { label: "Medical practice - cenník", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/hn_cennik_2019_0312_mp_c.pdf", class: "product-detail-btn btn-specia3" },
          { label: "Medical practice - harmonogram", url: "https://mafraslovakia.hnonline.sk/files/title_schedule/LL%20+%20MP_harmonogram_2025.pdf", class: "product-detail-btn btn-special4" },
          { label: "Kompendium medicíny - harmonogram", url: "https://mafraslovakia.hnonline.sk/files/title_pricelist/mafra_produkt_listy_2025_kompendium-mediciny.pdf", class: "product-detail-btn btn-special6" }
        ]
      },
    10: {
        name: "Chvíľka pre teba",
        description: "Chvíľka pre teba je pre súťaživých čitateľov, ktorí majú radi krížovky, osemsmerovky, testy, kvízy a ďalšie lúštenie o zaujímavé a atraktívne ceny. Obsahom Chvíľky sú pravidelné rubriky, ako sú kuchárske recepty, stránky o zdraví a zdravom životnom štýle, o kozmetike, móde, cestovaní a ešte oveľa viac! Do rodiny časopisov pod značkou Chvíľka pre teba patrí: Chvíľka pre teba Krížovky a Chvíľka pre teba Varíme a pečieme.",
        zameranie: "Zameranie: lifestyle, súťaže, krížovky",
        vznik: "Vznik: 2007",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/chpt.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/chvilka_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/chvilka_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016052-chvilka-pre-teba", 
      },
    11: {
        name: "Top sestra",
        description: "Exkluzívna publikácia, ktorá na Slovensku vyjde tento rok už druhýkrát, prináša jedinečný zoznam TOP sestier. Po vlaňajšom vydaní, ktoré sa venovalo personálu v zdravotníckych zariadeniach, v roku 2025 oceníme sestry v ambulantnom sektore.Prostredníctvom rozhovorov s TOP sestrami prinášame pohľad do „zákulisia“ jednotlivých odborov. Publikácia TOP sestry na Slovensku prezentuje tých najlepších vo vybraných kategóriách – sestry zo všeobecných ambulancií pre dospelých, sestry zo všeobecných ambulancií pre deti a dorast a z pediatrických ambulancií, sestry zo špecializovaných ambulancií a sestry zo zubných ambulancií.",
        zameranie: "Zameranie: zdravotníctvo",
        vznik: "",
        periodicita: "",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tttttttttttt.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    12: {
        name: "Evita",
        description: "Populárna Evita – mesačník pre ženy už dekádu každý mesiac prináša skutočné príbehy skutočných žien a veľa inšpiratívneho čítania v podobe exkluzívneho magazínu. Je dlhodobo lídrom v kategórii najpredávanejší ženský mesačník.",
        zameranie: "Zameranie: ženský prémiový magazín",
        vznik: "Vznik: 2015",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/evita.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/evita_cennik_2025_0.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/evita_cennik_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    13: {
        name: "Evita Varíme spolu",
        description: "varímespolu.sk je online priestor pre všetkých, ktorí milujú dobré jedlo a spoločné chvíle pri varení. Nájdete tu overené recepty, tipy do kuchyne, sezónne inšpirácie aj nápady na rýchle a zdravé jedlá. Či už ste začiatočník alebo skúsený kuchár, u nás si určite vyberiete.",
        zameranie: "",
        vznik: "Vznik: 2022",
        periodicita: " ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tttttttttttt.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/evita_cennik_2025_0.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/evita_cennik_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    14: {
        name: "Všetko pre ženu",
        description: "Mesačník pre ženy v cieľovej skupine 35+ prináša pestrý mix oddychových tém, predovšetkým praktické rady a návody týkajúce sa každodenného života. Dôraz kladie na skutočné príbehy, ktoré časopisu posielajú samotné čitateľky, aby sa podelili o svoje životné skúsenosti, trampoty aj radosti a pomohli tak iným čitateľkám, ktoré sa ocitnú v podobnej životnej situácii. Prináša tiež ľahkou a jednoduchou formou spracované informácie o zdraví, oddych pri reportážach z ciest, pri krížovkách aj horoskopoch. Nechýbajú rady, ako sa zdravo stravovať, ako aj čitateľkami overené diéty.",
        zameranie: "Zameranie: ženský magazín",
        vznik: "Vznik: 2015",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/vsetkoprezenu.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/vsetko_pre_zenu_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    15: {
        name: "Tajomstvá ženy",
        description: "Ženský dvojmesačník zameraný na ženy 35+. Jeho výnimočnosť spočíva v tom, že všetky témy, ktoré sú v ňom publikované, sú nejakým spôsobom vždy prepojené aj so známou ženou, ktorá odkrýva svoje súkromie a životné skúsenosti. Nechýba v ňom nič, čo ženy milujú. Články o zdraví, kráse, recepty, horoskopy, kuriozity, cestovanie, rozhovory, krížovky, až 15 strán skutočných príbehov z pera samotných čitateliek a rubrika Tajomstvá mužov, v ktorej zase čo-to zo svojho života odhaľuje vždy nejaký populárny muž.",
        zameranie: "Zameranie: ženský magazín",
        vznik: "Vznik: 2015",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tajmostvazeny.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/chvilka_pre_teba_tajomstva_zeny_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    16: {
        name: "Téma",
        description: "Nový spoločensko-spravodajský týždenník, ktorý prináša zaujímavé rozhovory, publicistiku a témy, ktoré ľudí najviac zaujímajú.",
        zameranie: "Zameranie: spoločnosť & lifestyle",
        vznik: "Vznik: 2017",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tema.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/tema_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/tema_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016050-rytmus-zivota", 
      },
    17: {
        name: "Rytmus života",
        description: "NAJPREDÁVANEJŠÍ spoločenský týždenník na Slovensku – Rytmus života je pestrou zmesou najčerstvejších noviniek z hviezdnej spoločnosti a zaujímavých informácií z mnohých odborov ľudskej činnosti. Slávne osobnosti tak spoznáte také, aké naozaj sú! S týmto časopisom pred vami nezostane nič utajené! Dozviete sa aj aktuálne módne trendy, kozmetické triky, rady pre zdravie, tipy na dovolenku, overené recepty z kuchyne, rady psychológa a ešte oveľa viac!Každý mesiac vychádza mimoriadne rozšírené XXL vydanie, kde si čitatelia na 64 stranách nájdu extra témy, recepty, krížovky a zaujímavosti zo života slávnych.Do rodiny Rytmu života patria Rodinné zdravie, Záhady a horoskopy, Naša záhrada, Rytmus života Varíme, Návraty hviezd, Krížovky. ",
        zameranie: "Zameranie: spoločenské témy",
        vznik: "Vznik: 2013",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/rytmuszivota.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/rytmus_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/rytmus_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      18: {
        name: "Rytmus života Rodinné zdravie",
        description: "Časopis pre ľudí v produktívnom veku. Svoje si v ňom však nájdu aj seniori či ľudia zameraní na zdravý životný štýl. Obsahom sú rôzne témy týkajúce sa zdravia: ako rozoznať ochorenie, ako si pomôcť, čo zaberá na jednotlivé diagnózy a ako sa im najlepšie vyhnúť. V jednotlivých rubrikách sa opierame o rady odborníkov, lekárov, fyzioterapeutov, cvičiteľov. Poradia, ako sa starať nielen o zdravie, o telo, ale aj o dušu. Čitateľ si nájde aj alternatívne spôsoby v starostlivosti o zdravie. Nechýbajú ani chutné zdravé recepty, príbehy zo života, zábavné testy či horoskop.",
        zameranie: "Zameranie: špeciál o zdraví a zdravom životom štýle patrí do rodiny RYTMUS ŽIVOTA",
        vznik: "Vznik",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/rytmuszdarvie.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/rodine_zdravie_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016064-rytmus-zivota-rodinne-zdravie", 
      },
      19: {
        name: "Rytmus života Varíme",
        description: "Podstatnú časť plne farebného časopisu tvorí vyše 45 receptov na chutné pokrmy, koláčiky či dezerty. Nechýbajú ani tipy od šéfkuchárov. O vzťahu k vareniu niečo prezradia aj rôzne známe osobnosti z televíznych obrazoviek. Magazín je určený pre začiatočníkov aj pokročilých „kuchtíkov“. V časopise si preto nájdete aj recept zobrazujúci jednotlivé kroky pri príprave. Nechýbajú ani rady pri výbere kuchynských pomocníkov.",
        zameranie: "Zameranie: špeciál o varení patrí do rodiny RYTMUS ŽIVOTA v rozsahu 32 strán",
        vznik: "Vznik",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/rytmusvarime.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/cennik.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/rytmus_varime_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      20: {
        name: "Záhady a horoskopy",
        description: "Časopis pre všetkých záujemcov o nadpozemské javy, príbehy zo života, ktoré fascinujú svojou mysterióznosťou, fanúšikov horoskopov, ale aj ľudí, ktorí sa chcú dozvedieť viac o mnohých poverách, mýtoch a čaroch. Nechýbajú pravidelné rubriky s odborníkmi, anjelská komunikácia, numerológia, magické varenie, lunárny kalendár, záhady minulosti ani psychosomatika.",
        zameranie: "Zameranie: špeciál o horoskope patrí do rodiny RYTMUS ŽIVOTA",
        vznik: "Vznik",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/zahadyahoroskopy.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/rytmus_zahady_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/rytmus_zahady_cennik_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016069-rytmus-zivota-zahady-a-horoskopy", 
      },
      21: {
        name: "Balans",
        description: "Časopis Balans vznikol v roku 2014, prvý rok vychádzal ako štvrťročník, od roku 2015 do roku 2019 ako dvojmesačník a od marca 2020 vychádza ako mesačník. Magazín je zameraný na zdravý životný štýl, motiváciu, alternatívnu medicínu, veci medzi nebom a zemou. Osloví čitateľov, ktorým nie sú ľahostajné ich telo ani duša. Cieľovú skupinu tvoria ženy aj muži zameriavajúci sa na zdravý životný štýl od 20 do 75 rokov. Obsahuje motivačné články, zameriava sa na alternatívnu medicínu, homeopatiu, prináša veľkú ezoterickú tému, recepty na zdravé bio jedlá, horoskop, feng šuej, rozhovor so zaujímavou osobnosťou, bylinkáreň, články o joge, kreatívne návody, ako si namaľovať liečivé mandaly, aj relaxačné maľovanky. V rubrike Na vlastnej koži prinášame zážitky z rôznych zážitkových seminárov, pobytov, kurzov či meditácií. Zaujímavosťou je meditačný plagát, ktorý pomôže čitateľom uvoľniť sa aj počas stresujúcich pracovných dní.",
        zameranie: "Zameranie: časopis pre rovnováhu tela aj duše, ktorý vás pozitívne naladí",
        vznik: "Vznik: 2014",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/balans.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/balans_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/balans_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016055-balans", 
      },
      22: {
        name: "Varíme a pečieme",
        description: "Je dvojmesačník plný chutných receptov s fotkami, ktoré sú navyše doplnené aj o kalorickú hodnotu daného jedla na jednu porciu a tiež o orientačný čas dĺžky jeho varenia či pečenia. Pre pestrosť sú doplnené aj krátke zaujímavosti o surovinách v jedle, ich výživovej hodnote, prípadne liečebných účinkoch na ľudský organizmus. Cieľová skupina sú ženy od 40 do 85 rokov.",
        zameranie: "Zameranie: špeciál o varení patrí do rodiny CHVÍĽKA PRE TEBA",
        vznik: "Vznik",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/chptvarime.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/chpt_varime_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      23: {
        name: "Noviny do pohody",
        description: "Spoločenský týždenník, ktorý je vyše desaťročia etablovaný na printovom trhu  a ponúka ten najkrajší pohľad na svet. Ak hľadáte príjemné, pozitívne čítanie bez politiky a tragických tém, Noviny do pohody sú práve pre VÁS. 32 strán čistej pohody na nostalgickom voňavom novinovom papieri ponúka zaujímavosti zo života známych osobností, praktické rady do domácnosti, chutné recepty, životné príbehy a lúštenie.  ",
        zameranie: "Zameranie: spoločenské témy",
        vznik: "Vznik: 2013",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/novinydopohody.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/Noviny_Do_Pohody_harmonogram%202025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      24: {
        name: "Čarovné Slovensko",
        description: "S mesačníkom Čarovné Slovensko objavíte tie najkrajšie stránky našej krajiny. V mesačníku Čarovné Slovensko sa dočítate: zaujímavých miestach, ktoré sa oplatí navštíviť, šikovných ľuďoch venujúcich sa tradičným remeslám, kúzelnej prírode a zvieratkách,všetkom slovenskom, o čom sa oplatí vedieť. A to všetko na unikátnych fotografiách s pekným grafickým spracovaním a reportážami, do ktorých redaktori vkladajú kus svojho srdca. <3",
        zameranie: "Zameranie: cestovanie po Slovensku",
        vznik: "Vznik: 2017",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/carovneslovensko.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/carovne_slovensko_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/carovne_slovensko_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016047-carovne-slovensko", 
      },
      25: {
        name: "Naša záhrada",
        description: "Dvojmesačník je orientovaný na všetky praktické témy týkajúce sa záhrady a riešenia záhradkárskych problémov. Svojim čitateľom titul predstaví známe aj menej známe rastliny a poradí pri pestovaní. Dvojmesačník Naša záhrada sa stane pomocou tak pre skúsených záhradkárov, ako aj začiatočníkov.",
        zameranie: "Zameranie: záhradkárske témy",
        vznik: "Vznik",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/nasazahrada.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/nasa_zahrada_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      26: {
        name: "Eurotelevízia",
        description: "Týždenník Eurotelevízia je najstarší a najprestížnejší programový magazín na Slovensku. Čitateľom prináša každý týždeň program až pre 94 staníc. K tomu na každý deň výber TV tipov, ktoré upozorňujú na najzaujímavejšie filmy, dokumenty, seriály, detské programy i športové prenosy. Časopis prináša exkluzívne rozhovory s hercami, moderátormi, televíznymi a filmovými tvorcami, ako aj pravidelné informácie z televízneho zákulisia, novinky z televízneho diania, ale aj zo sveta domáceho a zahraničného šoubiznisu, témy o prírode, vede i histórii, recepty, poradňu a články o zdraví.",
        zameranie: "Zameranie: televízny program",
        vznik: "Vznik: 1965",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/eurotelevizia.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/ETV_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/ETV_harmonogram_2025%20ok.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016048-eurotelevizia", 
      },
      27: {
        name: "TV max",
        description: "Dynamický dvojtýždenník TV Max v populárnom miniformáte vstúpil na slovenský trh v roku 2006 a od samého začiatku si získava veľkú obľubu medzi čitateľmi. Najmä medzi tými, ktorí sledujú trendy, žijú aktívne a potrebujú rýchly prehľad aj o televíznom vysielaní. Okrem bohatej ponuky TV programov pre 35 staníc časopis čitateľom prináša horúce novinky zo zahraničných seriálov, z filmov a iných programov, ktoré sa na Slovensku práve vysielajú.",
        zameranie: "Zameranie: televízny program",
        vznik: "Vznik: 2006",
        periodicita: "Periodicita: dvojtýždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tvmax.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/tv_max_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/tv_max_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016051-tv-max", 
      },
      28: {
        name: "Tele plus",
        description: "Vôbec prvý 14-denný programový časopis na Slovensku. Je určený všetkým, ktorí majú radi humor, či už tradičný kreslený, alebo vtipy, aforizmy, poviedky, spomienkové články o legendách televíznej obrazovky, novinky z TV zákulisia či cestovateľské tipy. Samozrejme, nemôže chýbať výber top TV tipov a TV program pre 35 staníc.",
        zameranie: "Zameranie: televízny program",
        vznik: "Vznik: 1990",
        periodicita: "Periodicita: dvojtýždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/teleplus.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/teleplus_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/teleplus_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016057-tele-plus", 
      },
      29: {
        name: "Telemagazín pre ženy",
        description: "Úspešne si udržiava svoje miesto na slovenskom mediálnom trhu už devätnásť rokov. Je určený všetkým, ktorí sa nielen so záujmom pozerajú na televíziu, ale taktiež radi súťažia, lúštia a varia. V každom vydaní totiž na čitateľa čaká nielen prehľadná ponuka 44 najsledovanejších televíznych programov s najhorúcejšími TV tipmi, ale aj novinky z TV zákulisia, krížovky a atraktívna výhra. Nízka cena časopisu je prijateľná pre každého televízneho diváka a pre každú domácnosť.",
        zameranie: "Zameranie: ženský časopis",
        vznik: "Vznik: 2006",
        periodicita: "Periodicita: týždenník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/telemagazin.png",
        btnCennik: "Cenník",
        btnCennikUrl: "https://mafraslovakia.hnonline.sk/files/title_pricelist/telemagazin_cennik_2025.pdf", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "https://mafraslovakia.hnonline.sk/files/title_schedule/Telemagazin_harmonogram_2025.pdf", 
        btnPred:"Predplatné",
        btnPredUrl: "https://hnonline.sk/predplatne/tlacene-tituly/96016063-tele-magazin-pre-zeny", 
      },
      30: {
        name: "Astro krížovky",
        description: "Dvojmesačník pre nadšencov lúštenia. Vychádza šesťkrát ročne a na 32 stranách ponúka nielen kopec zábavy s výhernými krížovkami, ale aj príjemný čas, relax a inšpiráciu k hlbším úvahám o zmysle našej pozemnej existencie a k hlbšiemu sebapoznávaniu a tým aj k rozvíjaniu porozumenia pre širšie súvislosti. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2014",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/astrokrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      31: {
        name: "Chvíľka na 100 krížoviek",
        description: "Vychádza štyrikrát do roka na 64 stranách. Okrem zábavných krížoviek prináša aj množstvo informácií o histórii, filme, literatúre či iných zaujímavostiach. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2017",
        periodicita: "Periodicita: štvrťročník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/100krizoviek.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      32: {
        name: "Chvíľka pre teba krížovky",
        description: "Vychádza 6-krát ročne ako doplnok k obľúbenému ženskému týždenníku Chvíľka pre teba. Maxikrížovky, švédske krížovky, číselné a maľované krížovky, tiež špeciálne tvary krížoviek a sudoku – to je to, čo na 32 stranách tento titul ponúka spoločne s množstvom zaujímavostí, vďaka ktorým sa lúštiteľ aj niečo užitočné dozvie. Vždy však ide o krátke články s pútavým obsahom, ktoré čitateľa/lúštiteľa nijako nezaťažia, ale sú skôr doplnkom ku krížovkám a kávičke.",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2014",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/chptkrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      33: {
        name: "Krížovky do vrecka",
        description: "Vychádzajú 6-krát ročne. Ideálny spoločník na cestovanie, vďaka malému formátu časopis hravo schováte aj do malej kabelky. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2006",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/krizovkydovrecka.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      34: {
        name: "Krížovky na každý deň",
        description: "Obľúbený krížovkársky mesačník vychádza v náklade viac ako 30-tisíc kusov. Na 32 stranách nájdete krížovky, ktoré vám ponúkajú skvelú zábavu, ale aj zaujímavosti a výročia, ktoré pripadajú na každý deň v mesiaci.",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2001",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/krizovkynakazdyden.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      35: {
        name: "Rytmus života krížovky s humorom",
        description: "Špeciálny dvojmesačník ako doplnok k najpredávanejšiemu ženskému týždenníku na trhu Rytmus života. Vychádza 6-krát do roka na 36 stranách. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2013",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/rytmuszivotakrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
     36: {
        name: "MAXI Krížovky plus",
        description: "Populárny dvojmesačník ako doplnok k MAXI KRÍŽOVKÁM, ktoré tiež vychádzajú v portfóliu vydavateľstva. Obsahujú 32 veľkoformátových krížoviek a zábavu pre celú rodinu. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2019",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/maxikrizovkyplus.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      37: {
        name: "Najlepšie krížovky",
        description: "Obľúbený dvojmesačník s bohatým obsahom, ktorý poteší lúštiteľa aj nelúštiteľa v každej jednej domácnosti. A navyše aj deti! V tomto titule majú vyhradené „svoje strany“, ktoré ich veľmi pobavia a vyplnia im voľný čas. Aj preto sa veková cieľová skupina začína už od 6 rokov! Skvelé krížovky dopĺňajú zaujímavosti a rady pre zdravie či skvelé recepty.",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2013",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/najlacnejsiekrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      38: {
        name: "Napínavé krížovky",
        description: "Obľúbený mesačník na 64 stranách plný skvelého lúštenia a výhier vychádza v náklade viac ako 80-tisíc kusov. Najpredávanejší krížovkársky mesačník na trhu je skvelým spoločníkom plným zaujímavých výherných krížoviek. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2001",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/napinavekrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      39: {
        name: "Napínavé krížovky plus",
        description: "Obľúbený mesačník na 64 stranách plný skvelého lúštenia a výhier vychádza v náklade viac ako 25-tisíc kusov. Doplnok k najpredávanejším krížovkám na trhu – Napínavým krížovkám. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2010",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/napinavekrizovkyplus.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      40: {
        name: "MAXI Krížovky zábava pre celú rodinu",
        description: "Krížovkársky mesačník pre nadšencov lúštenia je na trhu už od roku 1999. Je plný veľkoformátových krížoviek pre malých aj veľkých, skúsených i menej skúsených lúštiteľov. Jednoducho zábava pre celú rodinu. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 1999",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/maxikrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      41: {
        name: "Najlacnejšie krížovky (lúštime bez ouliarov)",
        description: "Dvojmesačník pre nadšencov lúštenia určený pre staršiu generáciu. Vďaka formátu a veľkosti krížoviek ich hravo zvládnete aj bez okuliarov či lupy.",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2011",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/tttttttttttt.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      42: {
        name: "Napínavé osemsmerovky",
        description: "Vychádza 6-krát ročne. Dvojmesačník pre milovníkov vyškrtávania zaujímavých osemsmeroviek na 32 stranách. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2014",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/osemsmerovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      43: {
        name: "Napísané životom krížovky",
        description: "Dvojmesačník pre hravých lúštiteľov, ktorí majú radi aj skvelé príbehy schované za krížovkami. Ideálny doplnok k obľúbenému časopisu Napísané životom. Vychádzajú 6-krát ročne na 48 stranách. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2017",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/napisanezivotomkrizovky.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      44: {
        name: "Krížovky a noviny",
        description: "Vychádzajú 6-krát ročne a sú plné skvelých krížoviek inšpirovaných známymi filmami či knižnými bestsellermi. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2002",
        periodicita: "Periodicita: dvojmesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/krizovkyanoviny.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
      45: {
        name: "Sudoku MINI",
        description: "Populárny mesačník pre milovníkov sudoku v skvelom formáte vychádza už dve desaťročia. Nájdete v ňom ľahké sudoku pre začiatočníkov, ale aj extrémne pre pokročilých. ",
        zameranie: "Zameranie: krížovky",
        vznik: "Vznik: 2005",
        periodicita: "Periodicita: mesačník ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "images/titulky/sudoku.png",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    };