    const products = {
      1: {
        name: "Hospodárske noviny",
        slug: "hospodarske-noviny",
        description: "Jediný ekonomický denník na Slovensku, ktorý svojím zameraním prináša seriózne a dôveryhodné informácie pre každého, koho zaujíma ekonomický pohľad na dianie doma a vo svete. Každý pracovný deň prinášajú aktuálne spravodajstvo, analýzy, štatistiky, prognózy a užitočné rady aj pre Váš druh podnikania.",
        zameranie: "Zameranie: Ekonomika, poradenstvo",
        vznik: "Vznik: 1993",
        periodicita: "Periodicita: denník",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    2: {
        name: "Produkt 1",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    3: {
        name: "Produkt 2",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    4: {
        name: "Produkt 3",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    5: {
        name: "Produkt 4",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    6: {
        name: "Produkt 5",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    7: {
        name: "Produkt 6",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    8: {
        name: "Produkt 7",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    9: {
        name: "Produkt 8",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    10: {
        name: "Produkt 9",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    11: {
        name: "Produkt 10",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    12: {
        name: "Produkt 11",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    13: {
        name: "Produkt 12",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    14: {
        name: "Produkt 13",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    15: {
        name: "Produkt 14",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    16: {
        name: "Produkt 15",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    17: {
        name: "Produkt 16",
        description: "",
        zameranie: "Zameranie: ",
        vznik: "Vznik: ",
        periodicita: "Periodicita: ",
        kontakt: "Kontakt: inzercia@mafraslovakia.sk",
        image: "https://static.svetevity.sk/pdfs/caputova.jpg",
        btnCennik: "Cenník",
        btnCennikUrl: "", 
        btnHarm:"Harmonogram",
        btnHarmUrl: "", 
        btnPred:"Predplatné",
        btnPredUrl: "", 
      },
    };